### ISSUE TITLE
Proposal: rename volumes

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#100]
From #95 

Proposed alternatives:
- `shared_directories`
- `common_directories`
- `common_data`
- `disk_paths`
- `directories`

**Comment by pditommaso** [comment]
Other proposals: 

* `mount_points` 
* `mount_paths`

**Comment by buchanae** [comment]
None of the proposed names are strike me as being more clear than `volumes`, and the term `volumes` is fairly close to the way Docker uses it. Also, the volume field specification has been simplified and the documentation improve substantially.

Feel free to suggest more names or a better description, but I'd like to take this off the TODO list.
