### ISSUE TITLE
Proposal: remove protobuf; switch to OpenAPI

### ISSUE THREAD

**Issue by aniewielska** [ga4gh/task-execution-schemas#109]
Now that WES has done [the move](https://github.com/ga4gh/workflow-execution-service-schemas/commit/120cd3b265e531855c4ae48046bf596a3e83329f) and transitioned towards OpenAPI, I would welcome getting rid of proto in TES as well. It seems that the idea got recognition at Toronto as well: ```OpenAPI vs. gRPC -- confirm OpenAPI -> formal issue and announcement``` [link](https://docs.google.com/document/d/1FreNnpyy2UueOI8ugX-WCd72OLJJmdTeyx9IR_E0DmA/edit#bookmark=id.y1jhp4vbp2v0). 
There seems to be nobody interested in calling TES via gRPC and for REST API OpenAPI is the right tool. With OpenAPI/Swagger such concepts as validation (required fields), optional fields, error description could be documented directly as parts of the spec and not only comments.

**Comment by stewartadam** [comment]
While we're on the topic of Swagger/OpenAPI migration - please leverage titles/descriptions to describe the models and avoid duplicate titles - per below many are lacking model names and are described as "output only", making it difficult to parent the model to where it's used.

![image](https://user-images.githubusercontent.com/77808/48524435-25ce7c00-e835-11e8-8d52-fe71e1954231.png)

**Comment by delagoya** [comment]
This is now complete as of PR #113. Closing.
