### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by delagoya** [ga4gh/task-execution-schemas#115]
Need to add a `CONTRIBUTING.md` file to outline the contribution process. In particular the move to using [HubFlow](http://datasift.github.io/gitflow/) for repo development. Probably easiest to copy over the one from the DRS repo.

**Comment by aniewielska** [comment]
We have CONTRIBUTING now and it is heavily inspired by WES, so to say. The document in DRS is far too large. We need to adopt branching strategy, I believe elements of HubFlow would work for us. This should probably be reflected in CONTRUBUTING document, as well. I will close this ticket and open a new one for branching and release strategy.
