### ISSUE TITLE
Frozen versions for TES spec

### ISSUE THREAD

**Issue by susheel** [ga4gh/task-execution-schemas#122]
To provide backward compatibility support TES servers/clients, we need to provide a frozen-in-time version of the spec. Suggest we keep a major-minor-version in the `/openapi` folder for the repo locked for any further edits.

`TES v1` --> `/openapi/`**`v1`**`/task_execution_service.swagger.yaml`
`TES latest` --> `/openapi/task_execution_service.swagger.yaml`

**OR**

`TES v1` --> `/openapi/task_execution_service.`**`v1`**`.swagger.yaml`
`TES latest` --> `/openapi/task_execution_service.swagger.yaml`

P.S. I would also suggest dropping `swagger` from the specification filename

**Comment by vsmalladi** [comment]
Can we close this?

**Comment by vsmalladi** [comment]
WE have tags, should be able to close this.

**Comment by uniqueg** [comment]
Yes, <https://github.com/ga4gh/workflow-execution-service-schemas/blob/<tag>/openapi/workflow_execution_service.openapi.yaml> should do the trick.

But note that for consistency, we should not change the filename and directory anymore. For example, for v1.1.0 it's `workflow_execution_service.openapi.yaml`, but for v1.0.0 it's `workflow_execution_service.swagger.yaml`.

Actually, the best would probably be `workflow_execution_service.yaml` (and have the client check the OpenAPI version).

Anyway, I vote for closing.
