### ISSUE TITLE
Provide JSON Schema definitions of the TES data model

### ISSUE THREAD

**Issue by susheel** [ga4gh/task-execution-schemas#123]
Provide JSON Schema definitions to help clients and services validate TES request/responses.

See WES [Issue #135](https://github.com/ga4gh/workflow-execution-service-schemas/issues/135) & [PR #136](https://github.com/ga4gh/workflow-execution-service-schemas/pull/136) as an example.

**Comment by vsmalladi** [comment]
doesn't seem to be used anymore

**Comment by uniqueg** [comment]
Agreed. We should keep in mind the HATEOAS aspects brought up in https://github.com/ga4gh/workflow-execution-service-schemas/issues/135 though. I think it could be very useful in some scenarios (and would turn our APIs into proper REST).

But yes, I think we can close the issue.
