### ISSUE TITLE
multiple uri for each output (one by protocole)

### ISSUE THREAD

**Issue by fjrmoreews** [ga4gh/task-execution-schemas#124]
The URL field seems limited. 
Is URL restricted to http / https ??? 
I propose to had a URI list for each output in the json task model.
This is a crucial point to extend the way we can implement the result files download for :

1/ high throughput use cases. 
2/ cloud provider integration.

A rest API doesn't mean that all dependent processes like upload and download are based on http.
example:
    "outputs" : [
      {
         "uri":["s3://","scp://","any://"]
        "url" :  "/path/to/output_file",
        "path" : "/container/output"
      }

for simplicity, URI list may replace the URL field as well :
 "outputs" : [
      {
         "uri":['"http://", "s3://","scp://","any://"]
        "path" : "/container/output"
      }
or even compact:
 "outputs" : [
      {
         "uri":[''file://', "http://", "s3://","scp://","any://"]
      }
with only http/https and file keys mandatory

similar idea for inputs

regards. 
F Moreews

**Comment by adamstruck** [comment]
Multiple protocols can be used in the URL, not just http/https. The implementation I work on, [Funnel](https://ohsu-comp-bio.github.io/funnel/), supports http/https, s3, google cloud storage, FTP and swift files.

**Comment by fjrmoreews** [comment]
Thanks Adam. I'm going to look at the Funnel implementation to see how you manage the URL field.
regards. Francois
