### ISSUE TITLE
Implement GA4GH service-info for TES

### ISSUE THREAD

**Issue by adamstruck** [ga4gh/task-execution-schemas#128]
Enables service discovery. 

Update: [ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification](https://github.com/ga4gh-discovery/ga4gh-service-info#how-to-use-and-extend-this-specification)

Suggestion in workstream call is to create a PR but leave it pending discussion of loose ends

**Comment by susheel** [comment]
Implemented in #129

**Comment by aniewielska** [comment]
GA4GH service-info has been in the end implemented in TES in #132 together with OpenAPI 3 migration and changed further in #143 and has already been incorporated to the approved version (v1.0, which we are about to release in the repo).
