### ISSUE TITLE
Plan for GA4GH Product Approval

### ISSUE THREAD

**Issue by susheel** [ga4gh/task-execution-schemas#130]
# GA4GH Task Execution Service Product Approval Planning

## Next submission window:
- (Open) 2020-04-16, (Close) 2020-07-12, (Deadline) 2020-09-12
- (Open) 2020-07-13, (Close) 2020-10-15, (Deadline) 2021-01-05 TBC

## Pending Actions:
- [ ] **Do we have support from Driver Projects?**
  - [ ] Chase DP contacts @rishidev Could you chase?
    - [x] ELIXIR - Jonathan Tedds
    - [ ] SPHN - 
    - [ ] GeL - Augusto Rendon
    - [ ] ICGC-ARGO - Christina Yung
    - [ ] EVA / ENA / EGA - Thomas Keane, Andy Yates
    - [ ] EJPRD - Sergi Beltran
    - [ ] ??Oliver Hoffmann (University of Melbourne)
    - [ ] CanDIG
  - [ ] Known external Users
    - [x] Illumina
    - [ ] Econican
    - [ ] Australian BioCommons
    - Others?
- [ ] **Do we have support from the Cloud WS?**
  - [ ] WES Co-lead support
  - [ ] DRS Co-lead support
- [ ] **Do we have reference implementations?**
  - [x] [Funnel](https://ohsu-comp-bio.github.io/funnel/)
  - [x] [TESK](https://github.com/EMBL-EBI-TSI/TESK)
  - [x] [tes-azure](https://github.com/microsoft/tes-azure)
- [ ] **Do we have support from upstream Implementors?**
  - [x] cwl-tes
  - [x] [Cromwell](https://cromwell.readthedocs.io/en/stable/backends/TES/)
  - [x] [Nextflow](https://www.nextflow.io/docs/latest/executor.html#ga4gh-tes)
  - [x] [Tesseract](https://github.com/ohsu-comp-bio/tesseract) 
  - [x] [TEStribute](https://github.com/elixir-cloud-aai/TEStribute)
- [ ] TES Spec cleanup for v1.0.0
  - [ ] Service info integration

**Comment by uniqueg** [comment]
@susheel or anyone with admin rights: could you please add [TEStribute](https://github.com/elixir-cloud-aai/TEStribute) as an upstream implementation? Thanks!

**Comment by rishidev** [comment]
@uniqueg This has been added to the initial comment

**Comment by aniewielska** [comment]
TES has been officially approved -> see [here](https://github.com/ga4gh/approval-tracker/issues/19) - the tracker still needs update.
