### ISSUE TITLE
Rename TaskParameter.{location, path} to have more meaningful names

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#14]
TaskParameter.location and TaskParameter.path refer to file locations on the storage drive and worker drive, respectively. While coding these into cromwell, we realized that these names weren't very intuitive and we kept needing to refer back to the TES proto spec to read the comments.

I think we can come up with better names that make the value of these attributes clear. My suggestion is 

location => storagePath
path       => containerPath

**Comment by kellrott** [comment]
The `location` field was original based on the `location` field in CWL: http://www.commonwl.org/v1.0/CommandLineTool.html#File

Instead of `location` or `storagePath` would `url` be useful?

**Comment by buchanae** [comment]
`url` works for me

**Comment by bwalsh** [comment]
Spoke to alex, agree it should be 'url'.  DMS currently has no concept of 'storage' vs 'container'  (it's implied that it would be 'storage')
