### ISSUE TITLE
Indicate Streamable files

### ISSUE THREAD

**Issue by kellrott** [ga4gh/task-execution-schemas#156]
Provide a flag that indicates that a file could be mounted via a streaming interface, if it is available, without causing performance degradation to the code being deployed.

**Comment by uniqueg** [comment]
Requested by Greek ELIXIR node, see https://docs.google.com/spreadsheets/d/1vBFhBQ-nFqhSL5dLjQfOWO6x9BzmV9x6l18p9GYRZdQ/edit#gid=0

Contacts: @zagganas & @vergoulis

**Comment by vsmalladi** [comment]
Closed by #157
