### ISSUE TITLE
Clarification required: executor command line variable interpolation

### ISSUE THREAD

**Issue by markjschreiber** [ga4gh/task-execution-schemas#164]
In the spec it appears that inputs are only allowed to be of the form:

```
{

    "url": "s3://my-object-store/file1",
    "path": "/data/file1"

}
```
Implying inputs must only be files.

Presumably non file variables required by the executors need to be provided either in file form or as environment variables for the appropriate executor?

If it is the former, is there a convention to be followed - like some kind of `inputs.json` standard?

If it is the latter, is there an assumed SHELL or simply the default shell of the container?

**Comment by uniqueg** [comment]
I think the executors model includes a field for specifying env vars to be defined in the container. Is that what you mean?

I don't think there's an assumed shell in the container - good point!

**Comment by markjschreiber** [comment]
I thinking of things like WDL tasks which allow inputs like `Int`, `String`, `Float`, `Struct` etc as well as `File`. The spec seemed to only allow URL and Path (effectively `File`).

**Comment by uniqueg** [comment]
I think the idea is that the TES client (e.g., the workflow engine) should provide any non-file inputs as part of the command line. In fact, that is expected for files as well.  The only reason `tesInput` and `tesOutput` are different is because files somehow need to be staged into/out of the executor environment.

What do you think @kellrott?

**Comment by vsmalladi** [comment]
I agree i think this is mostly to deal with staging of `files` and `directories`

**Comment by uniqueg** [comment]
There is surely a limitation (or gap?) in TES in that the standard is very file-centric. Inputs could potentially also be streams, messages, signals etc.

But since the issue does not clearly describe such a use case, it is hard to reason about it. I vote for closing.

**Comment by kellrott** [comment]
Regarding default shell: No default shell, expected to work similar to subprocess.Popen or [os.execvpe](https://docs.python.org/3/library/os.html#os.execvpe)

Regarding WDL style variables (ints string float): those are workflow language constructs, TES is meant to be a level below that. It's is working on the fork/exec into a container level. The input/output variables are there for mounting remote data

Regarding streams/messages/signals/IPC : Those I/O routes are usually limited single machines. IO streams don't translate to network traffic without a software stack supporting them. They could be added to the specification, but the implementations to ensure the multiple servers (Funnel, TESK, Azure-TES) all work the exact same way in different deployment topologies would be very extensive
