### ISSUE TITLE
Add user id field to DockerExecuter

### ISSUE THREAD

**Issue by adamstruck** [ga4gh/task-execution-schemas#17]
User identity within container should be configurable.  If 'None' container is executed as the user defined within the Dockerfile.

**Comment by buchanae** [comment]
What's the case where a user of a tool needs to override the user defined in the Dockerfile?

**Comment by adamstruck** [comment]
We tried this approach out over the last month or so and ran into several cases where this solution caused a workflow or tool to fail. 

TLDR this approach changes some environmental variables inside the container and that can cause tools to break.
