### ISSUE TITLE
Proposal: Add ability to optionally localize input files for tasks

### ISSUE THREAD

**Issue by vsmalladi** [ga4gh/task-execution-schemas#182]
**Problem:**
Cromwell's GCP backend supports optional localization of files, such as in this example:
https://github.com/broadinstitute/warp/blob/2b0493125cae26b71fb8eecf278d63104c573772/tasks/broad/ImputationTasks.wdl#L95

Add the ability to choose to localize or stream files for tasks.

**Solution**
Add in new localize variable to tesInputs

Linked to this issue: https://github.com/microsoft/CromwellOnAzure/issues/419

**Comment by kellrott** [comment]
I believe this overlaps with issue #156 and PR #157

**Comment by vsmalladi** [comment]
@kellrott Yes it seems to. We might want to discuss what the best term to call this is and what the default behavior is between streaming and localizing.

Adding @MattMcL4475 to the discussion.

**Comment by vsmalladi** [comment]
closing issue will be covered by issue #156  and PR #157
