### ISSUE TITLE
Proposal: New TES State for Preemption

### ISSUE THREAD

**Issue by vsmalladi** [ga4gh/task-execution-schemas#183]
Problem:
Cloud platform support preemption of machines. Cromwell needs a way to understand that state to implement the correct logic of dealing with task resubmission

Solution
Add in new state to tesState: "Preempted"

Linked to this issue: https://github.com/microsoft/CromwellOnAzure/issues/451

**Comment by patmagee** [comment]
I would be interested to know what the general consensus on this topic is. But If you do decide to go ahead with It, we would welcome a similar issue on the WES side

**Comment by vsmalladi** [comment]
@patmagee This was merged into 1.1. #184 

Can you open an issue on WES and I can help with the PR.
