### ISSUE TITLE
Proposal: TES-next

### ISSUE THREAD

**Issue by claymcleod** [ga4gh/task-execution-schemas#214]
Hi all!

As I've been exploring TES, I think there are quite a lot of things that have been done well. It's a great foundation to build on. To that end, I wonder if we could consider making a `next` branch where the next breaking change version could be iterated on. Critically, I think the ability to iterate without a lot of process (until the very when the release is ratified, of course) is going to be important to making progress quickly.

Just curious if this is something the spec maintainers would be open to? If so, I'd be happy to start incorporating thoughts on TES v2 into a project that could be viewed and considered.

**Comment by uniqueg** [comment]
I think this is a good idea. We should have a branch for 1.2 and 2.0, for non-breaking and breaking (or more complex) changes, respectively. With an aim to release 1.2 ideally before the end and 2.0 in 2025. Thoughts, @vsmalladi & @kellrott?

**Comment by vsmalladi** [comment]
I agree this is a good idea. I can crate some branches .

**Comment by vsmalladi** [comment]
Created two branches develop-v1.2 and develop-v2.0
