### ISSUE TITLE
Hardware accelerator resource requests.

### ISSUE THREAD

**Issue by claymcleod** [ga4gh/task-execution-schemas#217]
Some workflow languages, like [WDL](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#hardware-accelerators-gpu-and--fpga) and [Nextflow](https://www.nextflow.io/docs/latest/process.html#accelerator) have facilities for requesting nodes with different accelerators. I don't see any facility for requesting those in TES, so we should consider adding directives to handle these.

**Comment by vsmalladi** [comment]
Agreed @claymcleod can you add you comments to #163

**Comment by claymcleod** [comment]
Okay, apologies, I didn't search before I opened this. I'll close it in favor of #163.
