### ISSUE TITLE
Expand ServiceInfo message

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#28]
The ServiceInfo message currently contains only a map<string,string> for storage configuration, but storage configuration is likely more complex than a simple string to string map. For reference:

```proto
//Information about Task Execution Service
//May include information related (but not limited to)
//resource availability and storage system information
message ServiceInfo {
  //System specific key/value pairs
  //Example for a shared file system based storage system:
  //storageType=sharedFile, baseDir=/path/to/shared/directory
  map<string,string> storageConfig = 1;
}
```

Funnel's storage configuration currently includes (Go code):
```go
type LocalStorage struct {
	AllowedDirs []string
}

type S3Storage struct {
	Endpoint string
	Key      string
	Secret   string
}
```

Packing these into a map<string,string> requires some trick, such as a composite key such as "Local.AllowedDirs". Having to define custom string packing/unpacking when we're using protobuf everywhere else feels wrong; it adds complexity and therefore a source of bugs and confusion.

**Comment by buchanae** [comment]
Are there specific examples of data people would like to see in this field? Maybe that would help resolve any confusion about how to pack data into this property. And possibly I'm the only one who is confused :)

**Comment by geoffjentry** [comment]
This is more a general comment as I haven't thought deeply about this.

I think in all of these APIs we should strive towards the more generic answer to these kinds of questions. So for instance in your example there's more structure than a simple KV, but will that level of structure *always* be there? IMO as long as more complicated structure *can* be expressed (e.g what you describe) the simpler format should be preferred.

That's not to say to be general for the sake of being general, but we should be clear that any implementation would have at least as much structure as we specify.

**Comment by buchanae** [comment]
My concern with generic fields is that they could lead to implementation-specific packing of data (JSON, INI, CSV, etc) which clients will then start coding against, somehow switching unpacking logic per-implementation. If that's the common case, the clients could use implementation specific API endpoints.

On the other end of the spectrum might be a structure with lots of optional fields. @geoffjentry would that be worse? At least that would remove variation in format and naming, although you might still need if-statements for optional fields.

Aside from that, I'm not sure what value clients get from this endpoint. For example, if I write a TES tutorial, what example code can I write to demonstrates the usefulness of this endpoint?

**Comment by buchanae** [comment]
Here's a possible solution (and enhancement):
```proto
message ServiceInfo {
  // Returns the name of the service, e.g. "ohsu-compbio-funnel"
  string name = 1;
  // Returns a documentation string, e.g. "Hey, we're OHSU Comp. Bio!"
  string doc = 2;
  // Lists some, but not necessarily all, storage locations supported by the service.
  // Must be in a valid URL format.
  // e.g. 
  // file:///path/to/local/funnel-storage
  // s3://ohsu-compbio-funnel/storage
  // etc.
  repeated string storage = 3;
}
```

I think that solves the original intent of the endpoint without introducing the potential for problems with generic fields.

**Comment by geoffjentry** [comment]
@buchanae Yeah I hear you. There's not a great solution in either direction. I tend to dislike lots of optionals but that's because I dislike clutter and always worry that it becomes a slippery slope to enable any random idea regardless of how good/bad it is. OTOH it *is* a path which allows for a lot of flexibility. Really the point behind my comment is I think every change to these APIs should be well thought out in terms of implications on multiple implementers, etc.

I really like the looks of your alternative. I won't claim to know if it solves your original problem but if you feel it does then :+1: from me.
