### ISSUE TITLE
Document Paused state

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#37]
If I understand correctly, the ability to pause a task is not required behavior for a TES implementation, but if the implementation can pause a task, the `Pause` state allows that to be represented.

Did I get that right?

If so, I'll add documentation to that effect to make it crystal clear.

Just curious, is there a current TES stakeholder that is interested in implementing pausing? In other words, is someone actually going to use this state?

**Comment by geoffjentry** [comment]
I'd be :-1: on any requirement for a `Pause` but I like having the ability to do so.

FWIW I am involved with a few projects where TES might possibly (emphasis on the use of possibly vs probably) be used. In none of those cases would pause be feasible as far as I know.

**Comment by buchanae** [comment]
Added a comment in #39 that implementations **may** support this (they are not required).
