### ISSUE TITLE
Maximum message size

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#44]
We need to specify some maximum size for most fields, especially fields with large strings like logs and input contents.

Would it be easier/better to specify a maximum message size?

Alternatively, do we need to document maximum sizes for "string" fields, and "repeated" fields, and "map" fields?

**Comment by geoffjentry** [comment]
My only comment on this topic whenever it comes up is that the API *must* provide *some* mechanism for me to obtain the full thing. If that's a pointer to a file or something like that, that's AOK. Other than that I don't really care.

**Comment by buchanae** [comment]
@geoffjentry I realize now that I was specifically thinking of the maximum message size of a task submitted to RunTask. So, maximum **input** message.

**Comment by geoffjentry** [comment]
Oh, I totally misunderstood. 

I like the idea on paper but this feels like it could run afoul of the "640K should be enough for anyone" type of thing. Is this for a single input datum or for the entire thing?

**Comment by buchanae** [comment]
Ya, maybe it's better to just let implementations decide what size they support instead of specifying it in the spec?

I was thinking for the whole Task message, but I'm leaning towards closing this now.

**Comment by geoffjentry** [comment]
Yeah if it is the whole thing I was picturing a case where there were e.g. 100k files being input, each with a long bucket path. It can add up quickly.

**Comment by buchanae** [comment]
I think this is probably best left up to implementations, at least for now. I'm not sure we can pick a reasonable number that covers all implementations, nor am I sure there's much value to that. So, I'm going to close this.
