### ISSUE TITLE
make sure the endpoints definitions are documented

### ISSUE THREAD

**Issue by mdmiller53** [ga4gh/task-execution-schemas#48]
if the protobuf endpoints are documented properly, then the low-level documentation for them can be auto-generated.  detailsw how to do this coming in a week or two

**Comment by mdmiller53** [comment]
we're actually generating documentation for our google endpoint api's, so just using protobuf for a rest service might be different.  but our code is in our readthedocs github repository, [api_v2_script.py](https://github.com/isb-cgc/readthedocs/blob/master/api_v2_script.py), in case this helps.

**Comment by buchanae** [comment]
Working on generating docs here:
https://github.com/buchanae/task-execution-schemas/blob/gen-docs/genout/task_execution.proto.md

**Comment by buchanae** [comment]
@mdmiller53 we have a basic description in the README, and we have an issue for a more complete user guide in #49 

Is there anything left to do here?

**Comment by delagoya** [comment]
Closing issue. 

Generally we are moving to OpenAPI specification and will deal with documentation enhancements once the documentation build system is up and running.
