### ISSUE TITLE
Consider task batch

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#55]

**Comment by geoffjentry** [comment]
I'm working on a project wher we are considering doing exactly this. If it plays out the idea was to come up with a working example and then propose the changes back into TES. Still too early to provide much in the way of details or even commit to anything but figured it was worth noting

**Comment by buchanae** [comment]
@geoffjentry Sounds great, thanks. Looking forward to that.

An open question is what guarantees are made by this endpoint. Does this guarantee that tasks are saved in the system (database, queue, etc)?

Another consideration is the size of a batch with 10K tasks that each need a 1 KB "contents" parameter. What does the spec recommend in this case?

Another is how the user retrieves these tasks from ListTasks(). Related to #57

**Comment by geoffjentry** [comment]
Yeah so the primary question is if tes satisfies the use case and all the participating parties. If so at that point it'll be mapping what we need on top of it. If it works for tes great and if not so be it

**Comment by pditommaso** [comment]
What's the difference between this proposal and task arrays #60 ?

**Comment by buchanae** [comment]
@pditommaso I think the original difference was that this is a simple `BatchCreateTask(tasks []Task)`, i.e. send it a list of task messages, whereas #60 includes some idea of templating.

**Comment by buchanae** [comment]
I'm going to close this because:
- large batches introduce new considerations for request handlers
- there's no driving use case I know of
- batches (and retries on request failure) are easily handled by client-side code
