### ISSUE TITLE
Multiple docker executions and logs

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/task-execution-schemas#7]
Hi,
I've been working my way through the (swagger) schema and I have a few questions. 

1) The schema seems to indicate that `ga4gh_task_execTask` will have an array of docker executions that are run sequentially. I may be answering my own question here, but would it be correct to assume a naive interpretation here?  i.e. all input files are provisioned in in one working directory, each of the docker executions are run sequentially (simply one after another), and then all output files are provisioned out from the working directory? Or is there something more complex going on here?

2) How do you envision the sequential running of Docker containers interacting with the workflow execution schema? Is the dividing line that this schema will only allow the simplest DAG (i.e. a line of sequential tasks) and the workflow execution schema will allow for more complex structures?

Is the idea that an implementation of the workflow-execution-schema could be expected to be intelligent enough to "group" tasks in a more complex DAG to take advantage of the task-execution-schema's ability to group tasks? 

Adding to discussion @kellrott @briandoconnor

**Comment by kellrott** [comment]
The idea of the array of docker containers is allow multiple operations (that may require different command lines and different containers) occur on the same node, in an atomic batch. There is no design to use it to drive a DAG of operations. The array of command is supposed to be run sequentially.

**Comment by denis-yuen** [comment]
I think this has been elaborated on sufficiently.
