### ISSUE TITLE
Instructions for using .proto

### ISSUE THREAD

**Issue by psafont** [ga4gh/task-execution-schemas#93]
I've tried generating swagger from the proto file, but the instructions are missing.

What I've done
- $GOPATH was set.
- dependencies were downloaded:
`$ go get -u github.com/grpc-ecosystem/grpc-gateway`

- built protoc-gen-swagger:
`$ go build github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger`

After that, I get the following error:

```
$ make
protoc -I ./ -I /home/psafont/dev/ga4gh/task-execution-schemas/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/  \
        --swagger_out=logtostderr=true:. \
        task_execution.proto
protoc-gen-swagger: program not found or is not executable
--swagger_out: protoc-gen-swagger: Plugin failed with status code 1.
make: *** [Makefile:13: swagger] Error 1
```
The progra is in pwd, so there's something I'm obviously missing as a go neophyte, any directions?

**Comment by buchanae** [comment]
Possibly you need to add `export PATH=$PATH:$GOPATH/bin` ? In other words, add Go's bin directory to your path?

**Comment by psafont** [comment]
I'll try, thanks!

**Comment by psafont** [comment]
Yeah, just did `make install-tools` and `make`.
Should have read the Makefile more carefully.
